<a href="https://colab.research.google.com/github/janeshnanda2005/Accesstoken/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
ar = np.array([23,3,3,3,3,3])
print(ar)
dr = np.array(45)
print(dr)

[23  3  3  3  3  3]
45


In [ ]:
darry = np.array([[1,2,3],[4,5,6]])
print(darry)
# displays the dimension
print(darry.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
k = np.array([1,2,2])
#indexing
print(k[0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1


In [ ]:
catch = np.array([[1, 2, 3, 4],[6, 7, 8, 9]])
#silcing
print(catch[1,1])


7


In [3]:
#access the values from start to endpoint
np.arange(50,60,1),np.arange(50,60,2),np.arange(20,50,2)

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([50, 52, 54, 56, 58]),
 array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]))

In [ ]:
#to get the random numbers in float
np.random.uniform(5,10,size=4)
np.random.uniform(10,15,size = 10)

array([11.3843963 , 14.47653465, 13.14007609, 10.87468485, 11.49464989,
       11.75208327, 11.70151748, 14.60287534, 13.6864829 , 12.51117483])

In [ ]:
np.random.uniform(50,60,size = 6)


array([58.40544912, 59.60193908, 50.86753032, 50.0229582 , 53.32465565,
       59.72250703])

In [7]:
# generate random numbers in float
np.random.rand(1,2)
np.random.rand(10,12)
np.random.randint(10,20,size = 10)

array([18, 16, 18, 16, 15, 19, 16, 16, 18, 15])

In [ ]:
np.random.random_integers(1,10)#return sthe random intgers

<ipython-input-23-c8e21f3575da>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10)


4

In [ ]:
# prompt: data type int64
# matrix shape (1, 1, 1, 1, 4)
# dimension 5
# size 4
# item size in Bytes 8
# array size in Bytes 32 give code for this'

import numpy as np

# Create a 5-dimensional array with shape (1, 1, 1, 1, 4) and data type int64
my_array = np.zeros((1, 1, 1, 1, 4), dtype=np.int64)

# Fill the array with some sample data (you can change this)
my_array[0, 0, 0, 0, :] = [10, 20, 30, 40]


# Print array information
print("Data type:", my_array.dtype)
print("Shape:", my_array.shape)
print("Dimensions:", my_array.ndim)
print("Size:", my_array.size)
print("Item size (bytes):", my_array.itemsize)
print("Array size (bytes):", my_array.nbytes)

data type int64
matrix shape (1, 1, 1, 1, 4)
dimension 5
size 4
item size in Bytes 8
array size in Bytes 32


In [ ]:
dr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(dr.dtype)# represent the datatype
print(dr.itemsize)#displays th item size
print(dr.ndim)# display the size of aray
print(dr.shape)#returns the rows and colums
print(dr.nbytes)#retruns the bytes
print(dr.size)#retrns the totla element present in it

int64
8
2
(2, 5)
80
10


In [35]:
dx = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]])
print(dx)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [ ]:
arr = np.array([[0,1,2,3,4,5]])
print(arr)
y = [arr % 2 == 0]
print(y)

[[0 1 2 3 4 5]]
[array([[ True, False,  True, False,  True, False]])]


In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr[0][1]

2

In [12]:
arr[:,1:3]

array([[2, 3],
       [7, 8]])

In [13]:
arr.shape

(2, 5)

In [16]:
arr.reshape(1,-1),arr.ravel(),arr.flatten()

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [20]:
v = np.unique(arr)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [34]:
new = np.zeros(10).reshape(5,2)
new

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
dx

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [38]:
dx.sum()

300

In [40]:
dx.ndim,dx.shape

(3, (2, 2, 6))

In [42]:
dx+dx*2

array([[[ 3,  6,  9, 12, 15, 18],
        [21, 24, 27, 30, 33, 36]],

       [[39, 42, 45, 48, 51, 54],
        [57, 60, 63, 66, 69, 72]]])

In [51]:
np.arange(10,50).reshape(20,2),np.arange(10,50).reshape(8,5)

(array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]))

In [54]:
m = np.arange(10,50).reshape(20,2)

In [55]:
m.dtype

dtype('int64')

In [60]:
np.zeros(10)+np.ones(10)*1000

array([1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000.])

In [61]:
m+m//2

array([[15, 16],
       [18, 19],
       [21, 22],
       [24, 25],
       [27, 28],
       [30, 31],
       [33, 34],
       [36, 37],
       [39, 40],
       [42, 43],
       [45, 46],
       [48, 49],
       [51, 52],
       [54, 55],
       [57, 58],
       [60, 61],
       [63, 64],
       [66, 67],
       [69, 70],
       [72, 73]])

In [63]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])